
sc triggerinfo AppReadiness start/machinepolicy
sc triggerinfo AppIDSvc start/machinepolicy 
sc triggerinfo Appinfo start/machinepolicy 
sc triggerinfo AppMgmt start/machinepolicy 
sc triggerinfo AppXSvc start/machinepolicy
sc triggerinfo BITS start/machinepolicy
sc triggerinfo BFE start/machinepolicy 
sc triggerinfo KeyIso start/machinepolicy 
sc triggerinfo EventSystem start/machinepolicy 
sc triggerinfo COMSysApp start/machinepolicy 
sc triggerinfo VaultSvc start/machinepolicy 
sc triggerinfo DsSvc start/machinepolicy 
sc triggerinfo DeviceAssociationService start/machinepolicy 
sc triggerinfo DeviceInstall start/machinepolicy
sc triggerinfo DsmSvc start/machinepolicy
sc triggerinfo embeddedmode start/machinepolicy
sc triggerinfo EFS start/machinepolicy
sc triggerinfo Eaphost start/machinepolicy
sc triggerinfo fdPHost start/machinepolicy
sc triggerinfo FDResPub start/machinepolicy
sc triggerinfo PolicyAgent start/machinepolicy
sc triggerinfo KPSSVC start/machinepolicy
sc triggerinfo KtmRm start/machinepolicy
sc triggerinfo lltdsvc start/machinepolicy
sc triggerinfo diagnosticshub.standardcollector.service start/machinepolicy
sc triggerinfo swprv start/machinepolicy
sc triggerinfo Netman start/machinepolicy
sc triggerinfo NcaSvc start/machinepolicy
sc triggerinfo netprofm start/machinepolicy
sc triggerinfo NetSetupSvc start/machinepolicy
sc triggerinfo defragsvc start/machinepolicy
sc triggerinfo PerfHost start/machinepolicy
sc triggerinfo pla start/machinepolicy
sc triggerinfo PlugPlay start/machinepolicy
sc triggerinfo WPDBusEnum start/machinepolicy
sc triggerinfo Power start/machinepolicy
sc triggerinfo wercplsupport start/machinepolicy
sc triggerinfo UmRdpService start/machinepolicy
sc triggerinfo RSoPProv start/machinepolicy
sc triggerinfo ShellHWDetection start/machinepolicy
sc triggerinfo sacsvr start/machinepolicy
sc triggerinfo svsvc start/machinepolicy
sc triggerinfo StorSvc start/machinepolicy
sc triggerinfo TieringEngineService start/machinepolicy
sc triggerinfo SystemEventsBroker start/machinepolicy
sc triggerinfo lmhosts start/machinepolicy
sc triggerinfo TimeBrokerSvc start/machinepolicy
sc triggerinfo vds start/machinepolicy
sc triggerinfo VSS start/machinepolicy
sc triggerinfo Wcmsvc start/machinepolicy
sc triggerinfo Wecsvc start/machinepolicy
sc triggerinfo FontCache start/machinepolicy
sc triggerinfo msiserver start/machinepolicy
sc triggerinfo Winmgmt start/machinepolicy
sc triggerinfo TrustedInstaller start/machinepolicy
sc triggerinfo wmiApSrv start/machinepolicy